# Generated by Django 3.1.2 on 2020-11-13 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.IntegerField()),
                ('emi', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('interest_rates', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tenure', models.IntegerField()),
                ('total_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('N', 'NEW'), ('R', 'REJECTED'), ('A', 'APPROVED')], default='N', max_length=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
